name: clear_cache

on:
  workflow_dispatch:

jobs:
  ubuntu:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        release:
          - bionic
          - focal
          - jammy

    steps:
    - uses: actions/checkout@v2
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 2000M
        key: ubuntu-${{matrix.release}}
        verbose: 2
    - run: ccache -C