name: debuild

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      full:
        description: 'Full rebuild without ccache'
        required: false
        default: 0

jobs:
  ubuntu-bionic:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        max-size: 1000M
        key: ubuntu-bionic
    - name: Set fast mode
      run: echo "ARG_FAST=--build-arg FAST=1" >> ${GITHUB_ENV}
      if: github.event.inputs.full == 0
    - name: Build container
      run: docker build ${ARG_FAST} -t mmomtchev/libnode-ubuntu-bionic:latest ubuntu/bionic
    - name: Run container
      run: docker run -v ${CCACHE_DIR}:/ccache --env CCACHE_DIR=/ccache mmomtchev/libnode-ubuntu-bionic:latest
