name: debuild

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      full:
        description: 'Full rebuild without ccache'
        required: false
        default: 0
      node_version:
        description: 'Node.js version'
        required: false
        default: 16.15.1
      napi_version:
        description: 'node-addon-api version'
        required: false
        default: 5.0.0

jobs:
  ubuntu-binary:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        release:
          - bionic
          - focal
          - jammy

    steps:
    - uses: actions/checkout@v2
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        max-size: 2000M
        key: ubuntu-bionic
    - name: Set fast mode
      run: echo "ARG_FAST=--build-arg FAST=1" >> ${GITHUB_ENV}
      if: github.event.inputs.full == 0
    - name: Set Node version
      id: node_version
      run: |
        NODE_VERSION=${{ github.event.inputs.node_version }}
        echo '::set-output name=value::${NODE_VERSION:-"16.15.1"}'
    - name: Set node-addon-api version
      id: napi_version
      run: |
        NAPI_VERSION=${{ github.event.inputs.napi_version }}
        echo '::set-output name=value::${NAPI_VERSION:-"5.0.0"}'
    - name: Build container
      run: |
        docker build --build-arg ${{matrix.release}} ${ARG_FAST} \
          --build-arg RELEASE=${{matrix.release}} \
          --build-arg NODE_VERSION=${{steps.node_version.outputs.value}} \
          --build-arg NAPI_VERSION=${{steps.napi_version.outputs.value}} \
          -t mmomtchev/libnode-ubuntu-${{matrix.release}}:latest ubuntu
    - name: Run container
      run: |
        docker run -v `ccache --get-config=cache_dir`:/ccache --env CCACHE_DIR=/ccache \
          mmomtchev/libnode-ubuntu-${{matrix.release}}:latest


  ubuntu-source:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set Node version
      id: node_version
      run: |
        NODE_VERSION=${{ github.event.inputs.node_version }}
        echo '::set-output name=value::${NODE_VERSION:-"16.15.1"}'
    - name: Set node-addon-api version
      id: napi_version
      run: |
        NAPI_VERSION=${{ github.event.inputs.napi_version }}
        echo '::set-output name=value::${NAPI_VERSION:-"5.0.0"}'
    - name: Download Node.js source tarball
      run: |
        wget https://github.com/nodejs/node/archive/refs/tags/v${{steps.node_version.outputs.value}}.tar.gz \
          -O ubuntu/node_${{steps.node_version.outputs.value}}.orig.tar.gz
    - name: Extract the tarball
      run: |
        cd ubuntu && \
        tar zxvf node_${{steps.node_version.outputs.value}}.orig.tar.gz && \
        cp -a debian node-${{steps.node_version.outputs.value}}
    - name: Build the source package
      run: cd ubuntu && debuild --preserve-envvar=NAPI_VERSION --preserve-envvar=NODE_VERSION -S
      env:
        NODE_VERSION: ${{steps.node_version.outputs.value}}
        NAPI_VERSION: ${{steps.napi_version.outputs.value}}