name: debuild

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      full:
        description: 'Full rebuild without ccache'
        required: false
        default: 0
      node_version:
        description: 'Node.js version'
        required: false
        default: 16.15.1
      napi_version:
        description: 'node-addon-api version'
        required: false
        default: 5.0.0

jobs:
  ubuntu:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        release:
          - bionic
          - focal
          - jammy

    steps:
    - uses: actions/checkout@v2
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        max-size: 2000M
        key: ubuntu-${{matrix.release}}
    - name: Set fast mode
      run: echo "ARG_FAST=--build-arg FAST=1" >> ${GITHUB_ENV}
      if: github.event.inputs.full == 0
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{secrets.GPG_SIGNING_KEY}}
        git_user_signingkey: true
    - name: Set Node version
      run: |
        NODE_VERSION=${{github.event.inputs.node_version}}
        echo NODE_VERSION=${NODE_VERSION:-"16.15.1"} >> ${GITHUB_ENV}
    - name: Set node-addon-api version
      run: |
        NAPI_VERSION=${{github.event.inputs.napi_version}}
        echo NAPI_VERSION=${NAPI_VERSION:-"5.0.0"} >> ${GITHUB_ENV}
    - name: Prepare build container
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: mmomtchev
        password: "${{secrets.GITHUB_TOKEN}}"
        registry: docker.pkg.github.com
        image_name: libnode-ubuntu-${{matrix.release}}
        image_tag: latest
        context: ubuntu
        build_extra_args:
          ${{env.ARG_FAST}}
          --build-arg RELEASE=${{matrix.release}}
          --build-arg NAPI_VERSION=${{env.NAPI_VERSION}}
          --build-arg NODE_VERSION=${{env.NODE_VERSION}}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}    
    - name: Run build container
      run: |
        mkdir -p binary-${{matrix.release}}-${NODE_VERSION}
        docker run -v \
          `ccache --get-config=cache_dir`:/ccache --env CCACHE_DIR=/ccache \
          -v `pwd`/binary-${{matrix.release}}-${NODE_VERSION}:/out \
          -v ${HOME}/.gnupg:/root/.gnupg \
          mmomtchev/libnode-ubuntu-${{matrix.release}}:latest
    - uses: actions/upload-artifact@v3
      with:
        name: binary-${{matrix.release}}-${NODE_VERSION}
        path: binary-${{matrix.release}}-${NODE_VERSION}
